name: Build

on:
  - push
  - pull_request
  - workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installation d'Opam et OCaml
      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.2.0 

      # 3. Installation des dépendances via Opam
      - name: Install dependencies
        run: |
          opam depext alcotest menhir
          opam install -y graphics alcotest menhir

      # 4. Compilation (généralement via Dune)
      - name: Build project
        run: opam exec -- dune build

      # 5. Exécution des tests
      - name: Test examples 
        run: |
          cd tests
          dune test
