name: Opam

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.2.0
            
      - name: Install OCaml dependencies
        run: |
          opam depext alcotest menhir
          opam install graphics alcotest menhir
      
      - name: Build all examples
        run: |
          cd tests
          opam exec -- dune test
